--------------------------
--- USERS & PRIVILEGES ---
--------------------------

SELECT object_name, object_type
FROM all_objects
WHERE object_type IN ('TABLE', 'VIEW', 'FUNCTION', 'PROCEDURE') AND owner = 'C##PCBANG';

--- Admin

CREATE USER C##QTV IDENTIFIED BY 12345
  DEFAULT TABLESPACE T2
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON T1;

GRANT CONNECT, RESOURCE, CREATE SESSION TO C##QTV;
GRANT DBA TO C##QTV;

--- Giám đốc / Chủ kinh doanh

CREATE USER C##GD IDENTIFIED BY 12345
  DEFAULT TABLESPACE T2
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON T1;

GRANT CONNECT, RESOURCE, CREATE SESSION TO C##GD;

BEGIN
  FOR t IN (SELECT object_name FROM all_objects WHERE object_type = 'TABLE' AND owner = 'C##PCBANG') LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT ON C##PCBANG.' || t.object_name || ' TO C##GD';
  END LOOP;
END;
/

BEGIN
  FOR proc IN (SELECT object_name FROM all_objects WHERE object_type IN ('PROCEDURE', 'FUNCTION') AND owner = 'C##PCBANG') LOOP
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C##PCBANG.' || proc.object_name || ' TO C##GD';
  END LOOP;
END;
/

--- Quản lý

CREATE USER C##QuanLy IDENTIFIED BY 12345
  DEFAULT TABLESPACE T2
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON T1;

GRANT CONNECT, RESOURCE, CREATE SESSION TO C##QuanLy;

GRANT SELECT, INSERT ON KhachHang TO C##QuanLy;
GRANT SELECT, INSERT ON TTMay TO C##QuanLy;
GRANT SELECT, INSERT ON HoaDon TO C##QuanLy;
GRANT SELECT, INSERT ON CTHoaDonInternet TO C##QuanLy;
GRANT SELECT, INSERT ON CTHoaDonAnUong TO C##QuanLy;
GRANT SELECT, INSERT ON CTHoaDonDVKhac TO C##QuanLy;
GRANT SELECT, INSERT ON BaoTri TO C##QuanLy;
GRANT SELECT, INSERT ON SuKien TO C##QuanLy;
GRANT SELECT, INSERT ON ThamGiaSuKien TO C##QuanLy;
GRANT SELECT, INSERT ON DatCho TO C##QuanLy;
GRANT SELECT, INSERT ON GDNapTien TO C##QuanLy;

GRANT SELECT, INSERT ON NhanVien TO C##QuanLy;
GRANT SELECT, INSERT ON ViTriCV TO C##QuanLy;

GRANT SELECT ON ChiNhanh TO C##QuanLy;
GRANT SELECT ON Luong TO C##QuanLy;
GRANT SELECT ON BoPhan TO C##QuanLy;
GRANT SELECT ON HangTK TO C##QuanLy;
GRANT SELECT ON Zone TO C##QuanLy;
GRANT SELECT ON DVAnUong TO C##QuanLy;
GRANT SELECT ON PLDVAnUong TO C##QuanLy;
GRANT SELECT ON DVKhac TO C##QuanLy;
GRANT SELECT ON ThietBi TO C##QuanLy;

BEGIN
  FOR proc IN (SELECT object_name FROM all_objects WHERE object_type IN ('PROCEDURE', 'FUNCTION') AND owner = 'C##PCBANG') LOOP
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C##PCBANG.' || proc.object_name || ' TO C##QuanLy';
  END LOOP;
END;
/

--- Nhân viên quầy

CREATE USER C##NVQuay IDENTIFIED BY 12345 DEFAULT TABLESPACE T2 TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, CREATE SESSION TO C##NVQuay;

GRANT SELECT, INSERT ON KhachHang TO C##NVQuay;
GRANT SELECT, INSERT ON TTMay TO C##NVQuay;
GRANT SELECT, INSERT ON HoaDon TO C##NVQuay;
GRANT SELECT, INSERT ON CTHoaDonInternet TO C##NVQuay;
GRANT SELECT, INSERT ON CTHoaDonAnUong TO C##NVQuay;
GRANT SELECT, INSERT ON CTHoaDonDVKhac TO C##NVQuay;
GRANT SELECT, INSERT ON BaoTri TO C##NVQuay;
GRANT SELECT, INSERT ON SuKien TO C##NVQuay;
GRANT SELECT, INSERT ON ThamGiaSuKien TO C##NVQuay;
GRANT SELECT, INSERT ON DatCho TO C##NVQuay;
GRANT SELECT, INSERT ON GDNapTien TO C##NVQuay;

GRANT SELECT ON ChiNhanh TO C##NVQuay;
GRANT SELECT ON HangTK TO C##NVQuay;
GRANT SELECT ON Zone TO C##NVQuay;
GRANT SELECT ON DVAnUong TO C##NVQuay;
GRANT SELECT ON PLDVAnUong TO C##NVQuay;
GRANT SELECT ON DVKhac TO C##NVQuay;
GRANT SELECT ON ThietBi TO C##NVQuay;

BEGIN
  FOR proc IN (SELECT object_name FROM all_objects WHERE object_type IN ('PROCEDURE', 'FUNCTION') AND owner = 'C##PCBANG') LOOP
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON C##PCBANG.' || proc.object_name || ' TO C##NVQuay';
  END LOOP;
END;
/

--- Tạo nhanh tài khoản nhân viên và cấp quyền

CREATE OR REPLACE PROCEDURE p_TaoTKNhanVien(
    p_username IN VARCHAR2,
    p_password IN VARCHAR2
)
IS
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER ' || p_username || ' IDENTIFIED BY ' || p_password;
    EXECUTE IMMEDIATE 'GRANT C##NVQuay TO ' || p_username;
    COMMIT;
END;
/

BEGIN
    p_TaoTKNhanVien('C##NVN10', '12345');
END;
/

--- Tạo nhanh tài khoản quản lý và cấp quyền

CREATE OR REPLACE PROCEDURE p_TaoTKQuanLy(
    p_username IN VARCHAR2,
    p_password IN VARCHAR2
)
IS
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER ' || p_username || ' IDENTIFIED BY ' || p_password;
    EXECUTE IMMEDIATE 'GRANT C##QuanLy TO ' || p_username;
    COMMIT;
END;
/

BEGIN
    p_TaoTKQuanLy('C##QLN10', '12345');
END;
/

--- Xoá nhanh tài khoản

CREATE OR REPLACE PROCEDURE p_XoaTK(
    p_username IN VARCHAR2
)
IS
BEGIN
    EXECUTE IMMEDIATE 'DROP USER ' || p_username || ' CASCADE';
    COMMIT;
END;
/

BEGIN
    p_XoaTK('C##QLN10');
END;